apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delivereats-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /api/restaurant
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 3000
      - path: /api/menu
        pathType: Prefix
        backend:
          service:
            name: menu-service
            port:
              number: 3000
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3000
      - path: /api/order
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 3000
      - path: /api/courier
        pathType: Prefix
        backend:
          service:
            name: courier-service
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-ui
            port:
              number: 80
